update files

diff --git a/.github/workflows/uncrustify-check.yml b/.github/workflows/uncrustify-check.yml
--- a/.github/workflows/uncrustify-check.yml
+++ b/.github/workflows/uncrustify-check.yml
@@ -38,6 +38,18 @@ jobs:
         make
         sudo make install
 
+    - name: Run Uncrustify Check
+      run: |
+        result=$(find . -type f \( -name "*.cpp" -o -name "*.hpp" \) -not -path "./uncrustify-uncrustify-0.77.1/*" -exec uncrustify --check -c uncrustify.cfg {} \; 2>&1)
+        if echo "$result" | grep -q "FAIL" ; then
+          echo "Uncrustify check failed for the following files:"
+          echo "$result" | grep "FAIL"
+          exit 1
+        else
+          echo "Uncrustify check passed for all files."
+          exit 0
+        fi
+
     # - name: Download Uncrustify Config
     #   run: |
     #     git clone git@github.com:QCoreTech/format.cmake.git
@@ -63,17 +75,7 @@ jobs:
     # Пример вывода при неуспехе:
     # Uncrustify check failed for the following files:
     # FAIL: ./src/main.cpp (File size changed from 1824 to 1664)
-    - name: Run Uncrustify Check
-      run: |
-        result=$(find . -type f \( -name "*.cpp" -o -name "*.hpp" \) -not -path "./uncrustify-uncrustify-0.77.1/*" -exec uncrustify --check -c uncrustify.cfg {} \; 2>&1)
-        if echo "$result" | grep -q "FAIL" ; then
-          echo "Uncrustify check failed for the following files:"
-          echo "$result" | grep "FAIL"
-          exit 1
-        else
-          echo "Uncrustify check passed for all files."
-          exit 0
-        fi
+
 
 
 
