update files

diff --git a/.github/workflows/uncrustify-check.yml b/.github/workflows/uncrustify-check.yml
--- a/.github/workflows/uncrustify-check.yml
+++ b/.github/workflows/uncrustify-check.yml
@@ -8,7 +8,7 @@ jobs:
   uncrustify-check:
     runs-on: ubuntu-latest
 
-    # steps:
+    steps:
     #   # Авторизация в репозитории с использованием SSH
     #   # данный шаг осуществляет авторизацию в репозитории, так как он приватный - это обязательно
     #   # uses webfactory/ssh-agent@v0.8.0 - библиотека упрощающая использование SSH
@@ -25,30 +25,30 @@ jobs:
     # чтобы настройки на машине разработчика совпадали с настройками при проверке
     # явно подтягиваем версию uncrustify-0.77.1
     # TODO: этот шаг занимает много времени, возможно можно кэшировать?
-    - name: Set up Uncrustify
-      run: |
-        sudo apt-get update
-        sudo apt-get install -y wget
-        wget https://github.com/uncrustify/uncrustify/archive/uncrustify-0.77.1.tar.gz
-        tar -xzvf uncrustify-0.77.1.tar.gz
-        cd uncrustify-uncrustify-0.77.1
-        mkdir build
-        cd build
-        cmake ..
-        make
-        sudo make install
+      - name: Set up Uncrustify
+        run: |
+          sudo apt-get update
+          sudo apt-get install -y wget
+          wget https://github.com/uncrustify/uncrustify/archive/uncrustify-0.77.1.tar.gz
+          tar -xzvf uncrustify-0.77.1.tar.gz
+          cd uncrustify-uncrustify-0.77.1
+          mkdir build
+          cd build
+          cmake ..
+          make
+          sudo make install
 
-    - name: Run Uncrustify Check
-      run: |
-        result=$(find . -type f \( -name "*.cpp" -o -name "*.hpp" \) -not -path "./uncrustify-uncrustify-0.77.1/*" -exec uncrustify --check -c uncrustify.cfg {} \; 2>&1)
-        if echo "$result" | grep -q "FAIL" ; then
-          echo "Uncrustify check failed for the following files:"
-          echo "$result" | grep "FAIL"
-          exit 1
-        else
-          echo "Uncrustify check passed for all files."
-          exit 0
-        fi
+      - name: Run Uncrustify Check
+        run: |
+          result=$(find . -type f \( -name "*.cpp" -o -name "*.hpp" \) -not -path "./uncrustify-uncrustify-0.77.1/*" -exec uncrustify --check -c uncrustify.cfg {} \; 2>&1)
+          if echo "$result" | grep -q "FAIL" ; then
+            echo "Uncrustify check failed for the following files:"
+            echo "$result" | grep "FAIL"
+            exit 1
+          else
+            echo "Uncrustify check passed for all files."
+            exit 0
+          fi
 
     # - name: Download Uncrustify Config
     #   run: |
