Update Uncrustify Check Workflow

diff --git a/.github/workflows/uncrustify-check.yml b/.github/workflows/uncrustify-check.yml
--- a/.github/workflows/uncrustify-check.yml
+++ b/.github/workflows/uncrustify-check.yml
@@ -27,30 +27,31 @@ jobs:
       run: |
         # Define a function to check and format files
         check_and_format() {
-          local file=$1
-          local tmpfile="${file}.tmp"
+            local file=$1
+            local tmpfile="${file}.tmp"
 
-          # Run Uncrustify check
-          uncrustify -c uncrustify.cfg --check -f "$file" -l CPP > /dev/null 2>&1
+            # Run Uncrustify check
+            uncrustify -c uncrustify.cfg --check -f "$file" -l CPP > /dev/null 2>&1
+            local exit_code=$?
 
-          # Print the exit code for debugging
-          echo "Exit code: $?"
+            # Print the exit code for debugging
+            echo "Exit code for $file: $exit_code"
 
-          # If check fails, format the file
-          if [ $? -ne 0 ]; then
-            echo "File $file does not conform to code formatting rules. Formatting..."
-            uncrustify -c uncrustify.cfg -f "$file" -o "$tmpfile"
-            git diff --no-index "$file" "$tmpfile" || true
-            mv "$tmpfile" "$file"
-          else
-            echo "File $file passed style checks."
-          fi
+            # If check fails, format the file
+            if [ $exit_code -ne 0 ]; then
+                echo "File $file does not conform to code formatting rules. Formatting..."
+                uncrustify -c uncrustify.cfg -f "$file" -o "$tmpfile"
+                git diff --no-index "$file" "$tmpfile" || true
+                mv "$tmpfile" "$file"
+            else
+                echo "File $file passed style checks."
+            fi
         }
 
         # Find and check/format CPP, C, H, HPP files
         find . -type f \( -name "*.cpp" -o -name "*.c" -o -name "*.h" -o -name "*.hpp" \) | while read -r file; do
-          echo "Checking and formatting $file"
-          check_and_format "$file"
+            echo "Checking and formatting $file"
+            check_and_format "$file"
         done
 
     - name: Display Files with Incorrect Formatting
