Update Uncrustify Check Workflow

diff --git a/.github/workflows/uncrustify-check.yml b/.github/workflows/uncrustify-check.yml
--- a/.github/workflows/uncrustify-check.yml
+++ b/.github/workflows/uncrustify-check.yml
@@ -26,14 +26,19 @@ jobs:
 
     - name: Run Uncrustify Check
       run: |
-        result=$(find . -type f \( -name "*.cpp" -o -name "*.hpp" \) -not -path "./uncrustify-uncrustify-0.77.1/*" -exec uncrustify --check -c uncrustify.cfg {} \; | grep -E "FAIL" || true)
-        if [ -n "$result" ]; then
-          echo "Uncrustify check failed for the following files:"
-          echo "$result"
-          exit 1
-        else
-          echo "Uncrustify check passed for all files."
-        fi
+        result=$(find . -type f \( -name "*.cpp" -o -name "*.hpp" \) -not -path "./uncrustify-uncrustify-0.77.1/*" -exec uncrustify --check -c uncrustify.cfg {} \;)
+        echo "$result" | grep -q "FAIL" && { echo "Uncrustify check failed for the following files:"; echo "$result"; exit 1; } || echo "Uncrustify check passed for all files."
+
+    # - name: Run Uncrustify Check
+    #   run: |
+    #     result=$(find . -type f \( -name "*.cpp" -o -name "*.hpp" \) -not -path "./uncrustify-uncrustify-0.77.1/*" -exec uncrustify --check -c uncrustify.cfg {} \; | grep -E "FAIL")
+    #     if [ -n "$result" ]; then
+    #       echo "Uncrustify check failed for the following files:"
+    #       echo "$result"
+    #       exit 1
+    #     else
+    #       echo "Uncrustify check passed for all files."
+    #     fi
 
     # - name: Run Uncrustify Check
     #   run: |
