Update Uncrustify Check Workflow

diff --git a/.github/workflows/uncrustify-check.yml b/.github/workflows/uncrustify-check.yml
--- a/.github/workflows/uncrustify-check.yml
+++ b/.github/workflows/uncrustify-check.yml
@@ -28,68 +28,11 @@ jobs:
       run: |
         result=$(find . -type f \( -name "*.cpp" -o -name "*.hpp" \) -not -path "./uncrustify-uncrustify-0.77.1/*" -exec uncrustify --check -c uncrustify.cfg {} \; 2>&1)
         echo "$result" | grep -q "FAIL"
-        # if [ $? -eq 0 ]; then
-        #   echo "Uncrustify check failed for the following files:"
-        #   echo "$result" | grep "FAIL"
-        #   exit 1
-        # else
-        #   echo "Uncrustify check passed for all files."
-        #   exit 0
-        # fi
-
-
-
-
-    # if echo "$result" | grep -q "FAIL"; then
-    #   echo "Uncrustify check failed for the following files:"
-    #   echo "$result" | grep "FAIL"
-    #   exit 1
-    # else
-    #  echo "Uncrustify check passed for all files."
-    # fi
-
-    # - name: Run Uncrustify Check
-    #   run: |
-    #     result=$(find . -type f \( -name "*.cpp" -o -name "*.hpp" \) -not -path "./uncrustify-uncrustify-0.77.1/*" -exec uncrustify --check -c uncrustify.cfg {} \; | grep -E "FAIL")
-    #     if [ -n "$result" ]; then
-    #       echo "Uncrustify check failed for the following files:"
-    #       echo "$result"
-    #       exit 1
-    #     else
-    #       echo "Uncrustify check passed for all files."
-    #     fi
-
-    # - name: Run Uncrustify Check
-    #   run: |
-    #     find . -type f \( -name "*.cpp" -o -name "*.hpp" \) -not -path "./uncrustify-uncrustify-0.77.1/*" -exec uncrustify --check -c uncrustify.cfg {} \;
-
-    # - name: Run Uncrustify Check
-    #   run: |
-    #     failed_files=""
-    #     while IFS= read -r -d $'\0' file; do
-    #       uncrustify --check -c uncrustify.cfg "$file"
-    #       if [ $? -ne 0 ]; then
-    #         failed_files="$failed_files $file"
-    #       fi
-    #     done < <(find . -type f \( -name "*.cpp" -o -name "*.hpp" \) -not -path "./uncrustify-uncrustify-0.77.1/*" -print0)
-    #
-    #     if [ -n "$failed_files" ]; then
-    #       echo "Файл(ы):$failed_files не соответствуют настройкам форматирования uncrustify."
-    #       exit 1
-    #     fi
-
-
-    # - name: Run Uncrustify Check
-    # run: |
-    #     failed_files=""
-    #     while IFS= read -r -d $'\0' file; do
-    #         uncrustify --check -c uncrustify.cfg "$file" >/dev/null 2>&1
-    #         if [ $? -ne 0 ]; then
-    #             failed_files="$failed_files $file"
-    #         fi
-    #     done < <(find . -type f \( -name "*.cpp" -o -name "*.hpp" \) -not -path "./uncrustify-uncrustify-0.77.1/*" -print0)
-    #
-    #     if [ -n "$failed_files" ]; then
-    #         echo "Файл(ы):$failed_files не соответствуют настройкам форматирования uncrustify."
-    #         exit 1
-    #     fi
+        if [ $? -eq 0 ]; then
+          echo "Uncrustify check failed for the following files:"
+          echo "$result" | grep "FAIL"
+          exit 1
+        else
+          echo "Uncrustify check passed for all files."
+          exit 0
+        fi
