Update Uncrustify Check Workflow

diff --git a/.github/workflows/uncrustify-check.yml b/.github/workflows/uncrustify-check.yml
--- a/.github/workflows/uncrustify-check.yml
+++ b/.github/workflows/uncrustify-check.yml
@@ -34,7 +34,14 @@ jobs:
       run: |
         result=$(find . -type f \( -name "*.cpp" -o -name "*.hpp" \) -not -path "./uncrustify-uncrustify-0.77.1/*" -exec uncrustify --check -c uncrustify.cfg {} \; 2>&1)
         echo "$result" | grep -q "FAIL"
-        grep -q "FAIL" $result && exit 1 || exit 0
+        if [ $? -eq 0 ]; then
+          echo "$result"
+          exit 1
+        else
+          exit 0
+        fi
+
+        # grep -q "FAIL" $result && exit 1 || exit 0
 
         # if [ $? -eq 0 ]; then
         #   echo "Uncrustify check failed for the following files:"
