Update Uncrustify Check Workflow

diff --git a/.github/workflows/uncrustify-check.yml b/.github/workflows/uncrustify-check.yml
--- a/.github/workflows/uncrustify-check.yml
+++ b/.github/workflows/uncrustify-check.yml
@@ -26,7 +26,16 @@ jobs:
 
     - name: Run Uncrustify Check
       run: |
-        find . -type f \( -name "*.cpp" -o -name "*.hpp" \) -not -path "./uncrustify-uncrustify-0.77.1/*" -exec uncrustify --check -c uncrustify.cfg {} \;
+        result=$(find . -type f \( -name "*.cpp" -o -name "*.hpp" \) -not -path "./uncrustify-uncrustify-0.77.1/*" -exec uncrustify --check -c uncrustify.cfg {} \; | grep -E "FAIL")
+        if [ -n "$result" ]; then
+          echo "Uncrustify check failed for the following files:"
+          echo "$result"
+          exit 1
+        fi
+
+    # - name: Run Uncrustify Check
+    #   run: |
+    #     find . -type f \( -name "*.cpp" -o -name "*.hpp" \) -not -path "./uncrustify-uncrustify-0.77.1/*" -exec uncrustify --check -c uncrustify.cfg {} \;
 
     # - name: Run Uncrustify Check
     #   run: |
